//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DummyClient.RemoteJms2 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://facade.messagemgmt.crypt.com/", ConfigurationName="RemoteJms2.MessagingEndpoint")]
    public interface MessagingEndpoint {
        
        // CODEGEN: Generating message contract since element name message from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://facade.messagemgmt.crypt.com/MessagingEndpoint/messageOperationRequest", ReplyAction="http://facade.messagemgmt.crypt.com/MessagingEndpoint/messageOperationResponse")]
        DummyClient.RemoteJms2.messageOperationResponse messageOperation(DummyClient.RemoteJms2.messageOperationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://facade.messagemgmt.crypt.com/MessagingEndpoint/messageOperationRequest", ReplyAction="http://facade.messagemgmt.crypt.com/MessagingEndpoint/messageOperationResponse")]
        System.Threading.Tasks.Task<DummyClient.RemoteJms2.messageOperationResponse> messageOperationAsync(DummyClient.RemoteJms2.messageOperationRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class messageOperationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="messageOperation", Namespace="http://facade.messagemgmt.crypt.com/", Order=0)]
        public DummyClient.RemoteJms2.messageOperationRequestBody Body;
        
        public messageOperationRequest() {
        }
        
        public messageOperationRequest(DummyClient.RemoteJms2.messageOperationRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class messageOperationRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string message;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string key;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string nameFile;
        
        public messageOperationRequestBody() {
        }
        
        public messageOperationRequestBody(string message, string key, string nameFile) {
            this.message = message;
            this.key = key;
            this.nameFile = nameFile;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class messageOperationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="messageOperationResponse", Namespace="http://facade.messagemgmt.crypt.com/", Order=0)]
        public DummyClient.RemoteJms2.messageOperationResponseBody Body;
        
        public messageOperationResponse() {
        }
        
        public messageOperationResponse(DummyClient.RemoteJms2.messageOperationResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class messageOperationResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool @return;
        
        public messageOperationResponseBody() {
        }
        
        public messageOperationResponseBody(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MessagingEndpointChannel : DummyClient.RemoteJms2.MessagingEndpoint, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MessagingEndpointClient : System.ServiceModel.ClientBase<DummyClient.RemoteJms2.MessagingEndpoint>, DummyClient.RemoteJms2.MessagingEndpoint {
        
        public MessagingEndpointClient() {
        }
        
        public MessagingEndpointClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MessagingEndpointClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MessagingEndpointClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MessagingEndpointClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DummyClient.RemoteJms2.messageOperationResponse DummyClient.RemoteJms2.MessagingEndpoint.messageOperation(DummyClient.RemoteJms2.messageOperationRequest request) {
            return base.Channel.messageOperation(request);
        }
        
        public bool messageOperation(string message, string key, string nameFile) {
            DummyClient.RemoteJms2.messageOperationRequest inValue = new DummyClient.RemoteJms2.messageOperationRequest();
            inValue.Body = new DummyClient.RemoteJms2.messageOperationRequestBody();
            inValue.Body.message = message;
            inValue.Body.key = key;
            inValue.Body.nameFile = nameFile;
            DummyClient.RemoteJms2.messageOperationResponse retVal = ((DummyClient.RemoteJms2.MessagingEndpoint)(this)).messageOperation(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DummyClient.RemoteJms2.messageOperationResponse> DummyClient.RemoteJms2.MessagingEndpoint.messageOperationAsync(DummyClient.RemoteJms2.messageOperationRequest request) {
            return base.Channel.messageOperationAsync(request);
        }
        
        public System.Threading.Tasks.Task<DummyClient.RemoteJms2.messageOperationResponse> messageOperationAsync(string message, string key, string nameFile) {
            DummyClient.RemoteJms2.messageOperationRequest inValue = new DummyClient.RemoteJms2.messageOperationRequest();
            inValue.Body = new DummyClient.RemoteJms2.messageOperationRequestBody();
            inValue.Body.message = message;
            inValue.Body.key = key;
            inValue.Body.nameFile = nameFile;
            return ((DummyClient.RemoteJms2.MessagingEndpoint)(this)).messageOperationAsync(inValue);
        }
    }
}
