//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgentWpfClient.DecipheringProgressService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DecipheringProgressService.IDecipheringProcessUpdater", CallbackContract=typeof(AgentWpfClient.DecipheringProgressService.IDecipheringProcessUpdaterCallback), SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface IDecipheringProcessUpdater {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IDecipheringProcessUpdater/ShowProgress")]
        void ShowProgress(string FileName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDecipheringProcessUpdaterCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IDecipheringProcessUpdater/Progress")]
        void Progress(string FileName, decimal Rounds, decimal TotalPossibilities, decimal Percentage);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDecipheringProcessUpdaterChannel : AgentWpfClient.DecipheringProgressService.IDecipheringProcessUpdater, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DecipheringProcessUpdaterClient : System.ServiceModel.DuplexClientBase<AgentWpfClient.DecipheringProgressService.IDecipheringProcessUpdater>, AgentWpfClient.DecipheringProgressService.IDecipheringProcessUpdater {
        
        public DecipheringProcessUpdaterClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public DecipheringProcessUpdaterClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public DecipheringProcessUpdaterClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public DecipheringProcessUpdaterClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public DecipheringProcessUpdaterClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void ShowProgress(string FileName) {
            base.Channel.ShowProgress(FileName);
        }
    }
}
